### ISSUE TITLE
SharePoint 2016 problem

### ISSUE THREAD

**Issue by NoralK** [gunjandatta/sp-event-callout#1]
Great script, however in SharePoint 2016 the script kills the Ribbon interface and disables the "Edit Page".  Had to use SharePoint Designer to remove it.  I hope this gets fixed as it is what I was looking for.

**Comment by gunjandatta** [comment]
The core JS code probably changed, or maybe the internal variable names. This happened between 2010 and 2013. I'll test this against SharePoint Online to see if I can get it to work there.

**Comment by NoralK** [comment]
Any update on this?

**Comment by gunjandatta** [comment]
I've tested this in 2013 and Online today, and the sample code works fine there. I don't have access to a 2016 install at the moment, so I'm not able to look at the JS files and/or debug. The target code is in the init method if you are able to debug it.

**Comment by gunjandatta** [comment]
Now that I have a 2016 environment, I'll test this out today.

**Comment by gunjandatta** [comment]
I've tested this in a SharePoint 2016 VM, and it worked as designed. I will make minor updates today, to ensure the latest versions of the library are being used.

The ribbon is still available, as well as editing the page. I will be closing this issue out, but please re-open it if you are still having issues. Please provide info on your site so I can recreate the issue.
