### ISSUE TITLE
Babel polyfill exception

### ISSUE THREAD

**Issue by mattweihl** [gunjandatta/sp-event-callout#2]
I am currently trying to use this script for a Calendar view in SharePoint 2013. It's an intranet site and uses Bonzai. I get an exception when trying to use this library along with Bonzai that states: "only one instance of babel-polyfill is allowed". 

Both Bonzai and this library use babel-polyfill. Do you have any suggested workarounds?

**Comment by gunjandatta** [comment]
I'll update and remove the reference to it. I have a better solution that expands on this one which I will try to release in the near future under a newer library (gd-sprest-webparts).

**Comment by gunjandatta** [comment]
I updated the project. Please re-open this issue if you still see the error.

**Comment by mattweihl** [comment]
That fixed it! Thanks!

**Comment by mattweihl** [comment]
Quick question: for the SPEventCallout(*list name*) constructor, how do I reference/ use a Calendar hosted on a different sub-site?
