### ISSUE TITLE
Issue with removing Calendar link and sp-event-callout

### ISSUE THREAD

**Issue by mattweihl** [gunjandatta/sp-event-callout#3]
I am currently in the process of integrating sp-event-callout to our company intranet portal. For the Calendar, I am removing links to event pages, and I just want the callout to appear (instead of going to the event's properties).

I am using jQuery. 
My code currently looks like: 
```
$("a[href*='***DispForm.aspx for event***").each(function () {
    $(this).contents().unwrap();
 });
```
However, when I do this, I can no longer hover to see the event details and clicking the link shows this:
![image](https://user-images.githubusercontent.com/6503635/29176480-94a96cd8-7db1-11e7-98ef-f289453e0507.png)

Tested in IE11 and Chrome 60 on Windows 7

Is there anyway to manually open the callout?

**Comment by gunjandatta** [comment]
The calendar will re-render the elements when you change the view from month, week or day. It also re-renders the elements when you change the month/week/day, so event if you apply logic to the elements it needs to be re-applied based on the calendar events. If you look at the code, you'll see where I add the code logic to the events. It's this method where you should apply your custom logic.
