### ISSUE TITLE
Vertical scrollbar appears when event callout appears on hover in IE11

### ISSUE THREAD

**Issue by mattweihl** [gunjandatta/sp-event-callout#4]
Hello.

I have noticed an issue with the callout and using it with a Calendar webpart. When hovering over an event that takes place on a Saturday, the calendar will shift over and a vertical scrollbar will appear.

This bug only occurs in IE11, this issue does not occur in Chrome.

Any suggestions/ fixes? 

OS: Windows 7
IE version: IE11
Chrome: 60

![image](https://user-images.githubusercontent.com/6503635/30748937-72cd7874-9f77-11e7-8d13-76d77ba195f0.png)

**Comment by mattweihl** [comment]
So as a temporary fix, I fixed the height of the Calendar web part, and that seemed to have fixed the issue, at least for now.

**Comment by gunjandatta** [comment]
This is just an example of a prototype and not a final solution. The callout hover event can be managed by the CalloutManager. I'll try to update this prototype on the weekend.

**Comment by gunjandatta** [comment]
I updated the code to use the CalloutManager to control the hover event. I've tested this in SP2013 and Online. For 2013, it works fine. For Online, depending on the "beakOrientation" you may see scroll bars so you'll probably have to add some styling to prevent this.

**Comment by gunjandatta** [comment]
Closing this issue out, as this project is really for a "hello world" example and meant to give developers a decent code example.
