### ISSUE TITLE
TypeScript not running in 2013

### ISSUE THREAD

**Issue by jbullfrog98** [gunjandatta/sp-event-callout#5]
Thank you for this much needed tool. I'm an inexperienced coder.  I followed the instructions, but am not seeing the callout window (still seeing the normal Sharepoint window).  
1. Is any special feature or service pack for Sharepoint 2013 needed to run TypeScript?
2. Is there a way to directly download the Library as a .js file.  I'm currently copying and pasting into Notepad and then saving as a .js file.  (I've tried saving as .txt file too).

**Comment by gunjandatta** [comment]
TypeScript is a superset of JavaScript. It will require you to compile the code, similar to server-side development (C# for instance). The source code you are reading is in TypeScript (.ts/.tsx), and the compiled version is in the ["dist" folder](https://github.com/gunjandatta/sp-event-callout/tree/master/dist). If you want to copy and paste code, then you'll have to copy the compiled javascript code.

Hope this helps.

**Comment by gunjandatta** [comment]
Closing this issue out, but feel free to open it back up if the "js" from the dist folder is causing you issues.

**Comment by gunjandatta** [comment]
I updated the code to include a second parameter for defining the fields to display:

new SPEventCallout("Calendar List Name", ["Title", "Category", "EventDate", "EndDate"]);
